server:
  port: 9090

spring:
  application:
    name: springboot-fastdfs

fdfs:
  so-timeout: 1500
  connect-timeout: 600
  thumb-image:
    width: 150
    height: 150
  tracker-list:
    - 192.168.1.254:22122
  web-server-url: http://192.168.1.254:8888/

